services:
  - type: web
    name: nft-showcase-backend
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.main:app --preload"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: nft-showcase-db
          property: connectionString
databases:
  - name: nft-showcase-db
    plan: free
    databaseName: nft_showcase
    user: nft_showcase_user
